SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INSERTARVENTA_DETALLE]
@IDVENT INT,
@FECVENDET DATETIME,
@PRECVENDET INT,
@IDEMP INT,
@IDPRO INT
AS
BEGIN

INSERT INTO 
VENTA_DETALLE
(IDVENT,FECVENDET,PRECVENDET,IDEMP,IDPRO)
VALUES
(@IDVENT,@FECVENDET,@PRECVENDET,@IDEMP,@IDPRO)
END
GO
