SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[INSERTARPERSONA] 
@NOMPER VARCHAR(50),
@APEPER VARCHAR(50),
@DNIPER CHAR(8),
@TELPER VARCHAR(9),
@DIRPER VARCHAR(100),
@TIPPER CHAR(1),
@IDUBIG INT
AS
BEGIN

INSERT INTO 
PERSONA
(NOMPER,APEPER,DNIPER,TELPER,DIRPER,TIPPER,IDUBIG)
VALUES
(@NOMPER,@APEPER,@DNIPER,@TELPER,@DIRPER,@TIPPER,@IDUBIG)
END
GO
