CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[IDVENT] [int] NOT NULL,
[FECVENDET] [datetime] NOT NULL,
[PRECVENDET] [int] NOT NULL,
[IDEMP] [int] NOT NULL,
[IDPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED  ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVENT]) REFERENCES [dbo].[VENTA] ([IDVENT])
GO
