CREATE TABLE [dbo].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIPER] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELPER] [varchar] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDUBIG] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_pk] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [EMPLEADOS_UBIGEO] FOREIGN KEY ([IDUBIG]) REFERENCES [dbo].[UBIGEO] ([IDUBIG])
GO
