CREATE TABLE [dbo].[USUARIO]
(
[IDUS] [int] NOT NULL IDENTITY(1, 1),
[NOMUS] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECINTRUS] [datetime] NOT NULL,
[ESTUS] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD CONSTRAINT [USUARIO_pk] PRIMARY KEY CLUSTERED  ([IDUS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD CONSTRAINT [USUARIO_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
